### PR TITLE
Subplots

### PR DESCRIPTION
**Pull request by fredrikclaesson-sick**
WIP: Please review for design choices

### CODE REVIEW

**Comment by fredrikclaesson-sick** [comment]
I am surprise that I got 100% code coverage? Is that really working? Can I see the code coverage somewhere?

**Comment by owodunni** [comment]
You can run the following to generate a code coverage report:
`pytest --pyargs GageRnR --cov-report html --cov=GageRnR --cov-fail-under 100 GageRnR/tests/ --junit-xml=build/test_results.xml`
This will generate a html report for you to watch.

**Comment by owodunni** [comment]
I think this looks fine.

For my understanding you are seperating creation of data to plot from the plotting. The reason for this is that you want to be able to plot the data yourself?

**Comment by owodunni** [comment]
Is it interesting to add the same seperation of data agregation and plotting even to the linearity plots?

https://github.com/owodunni/GageRnR/blob/b7b078d7c4103e2509c51989ade0dcd4c11f8b8a/GageRnR/linearity.py

**Comment by owodunni** [comment]
This has been release in GageRnR v0.8.0

**Pull request closed without merging**
